Documentation update for playbook feature
Venafi/vcert pull request #329
Opened 2023-08-02 21:31 UTC by fergven

Updated documentation for new playbook feature.

2023-08-02 23:37 UTC, jdw2465VEN commented on README-PLAYBOOK.md
> +- You don't have to pass long command line arguments. You can now call VCert with playbook YAML files, which helps with automation and maintenance.
Here's a suggestion to make this more scannable, which customers love; also some minor edits for clarity:

- **Simplified Commands**: With VCert Playbook, you can avoid long command-line arguments. Instead, use playbook YAML files with VCert to enhance automation and maintenance ease.
  
- **Flexible Certificate Placement**: You can designate where to place the certificate and the format in which you want it once received from Venafi. VCert Playbook supports common keystore formats like PEM, JKS, PKCS#12, accommodating folder locations and the Windows CAPI store.
  
- **Post-Installation Actions**: Specify any actions that must be carried out after the certificate is installed. This includes restarting services like Apache or Nginx, or running any other scripts needed once the certificate is in the right location.
  
- **Smart Certificate Renewals**: VCert Playbook checks if a certificate already exists and whether it's due for renewal before requesting a new one. This functionality lets you run a script regularly without unnecessarily renewing certificates.
  
- **Compatibility**: VCert Playbook works seamlessly with both TLS Protect Cloud and TLS Protect Datacenter, ensuring it fits your particular environment.

2023-08-02 23:37 UTC, jdw2465VEN commented on README-PLAYBOOK.md
> +- Renewal parameters can be setup to automatically renew the certificate before it expires. This model assumes that VCert is added to a daily cronjob or is executed on a regular basis by some other a
Same suggestion here and again with some suggested edits:

- **Automated Certificate Renewal**: You can set renewal parameters to have VCert automatically renew certificates before expiration. This approach assumes that VCert is part of a daily cronjob or is executed routinely through other automation methods. By default, renewal occurs at 10% of the remaining certificate lifetime.

- **Effortless API Access Updates**: When using TLS Protect Datacenter, VCert will automatically update API access and refresh tokens within the playbook. This feature ensures continuous operation without manual intervention. It leverages a refresh token to acquire a new access token when needed, an approach that's particularly effective when paired with a long-lasting refresh/grant token and a short-lived access token, such as a 3-year refresh token and a 1-hour access token.

2023-08-02 23:38 UTC, jdw2465VEN commented on README-PLAYBOOK.md
> +- You don't have to pass long command line arguments. You can now call VCert with playbook YAML files, which helps with automation and maintenance.
I should have made the bolded text sentence case, per our style guide

2023-08-02 23:46 UTC, rvelaVenafi requested changes
Added comments regarding the documentation

2023-08-02 23:46 UTC, rvelaVenafi commented on README-PLAYBOOK.md
> +### Credential
The object here is Credentials (plural) as stated in line 79

2023-08-02 23:46 UTC, rvelaVenafi commented on README-PLAYBOOK.md
> +| apikey       | string     | ***REQUIRED*** - when [Connection.platform](#connection) is `vaas`. *IGNORED* otherwise. |
`apikey` should be `apiKey` with an upper case K

2023-08-02 23:46 UTC, rvelaVenafi commented on README-PLAYBOOK.md
> +| clientId     | string     | *OPTIONAL* - Used when [Connection.platform](#connection) is `tpp` to map to the API integration to be used. If omitted, uses `vcert-cli` as default. *IGNORED* when [Con
default value for cliendId is `vcert-sdk` not `vcert-cli`

2023-08-02 23:46 UTC, rvelaVenafi commented on README-PLAYBOOK.md
> +| jksPassword          | string  | ***REQUIRED*** when [Installation.format](#installation) is `JKS`. Specifies the password for the JKS. *IGNORED* when [Installation.format](#installation) is not `J
Change JKS acronym here for Java Keystore to be consistent with jksAlias' description:
`Specifies the password for the Java Keystore`

2023-08-02 23:46 UTC, rvelaVenafi commented on README-PLAYBOOK.md
> +| location             | string |  ***REQUIRED*** when [Installation.format](#installation) is `CAPI`. Specifies the Windows CAPI store to place the installed certificate. Typically `"LocalMachine\My
regarding the quotes and double quotes, it is the opposite:
if location is in double quotes the backslash must be escaped:
`location: "LocalMachine\\My"`

if the location is in single quotes or no quotes, the backslash does not need escaping:
`location: 'LocalMachine\My'`

2023-08-02 23:46 UTC, rvelaVenafi commented on README-PLAYBOOK.md
> +| fields          | array of strings)      | *OPTIONAL* - Sets the specified custom field on certificate object. Only valid when [Connection.platform](#connection) is `tpp`. |
This is not an array of Strings, it is an array of `CustomField` object. Which I think is missing in the doc:

### CustomField

| Field   | Type      | Description |
|---------|-----------|-------------|
| name    | string    ||
| value   | string    ||

2023-08-02 23:46 UTC, rvelaVenafi commented on README-PLAYBOOK.md
> +| keySize         | integer                | *OPTIONAL* - Specifies the key size when specified [Request.keyType](#request) is `RSA`. Defaults to 2048. |
supported values for keySize are: `1024`, `2048`, `4096`, `8192`

2023-08-03 23:00 UTC, marcos-albornoz approved these changes

2023-08-03 23:02 UTC, luispresuelVenafi approved these changes

2023-08-09 03:06 UTC, fergven reviewed
Changes made

2023-08-09 03:06 UTC, fergven reviewed
Changes made

2023-08-09 03:07 UTC, fergven reviewed
Changes made

2023-08-09 03:10 UTC, fergven commented
> Added comments regarding the documentation

I've made all the changes.

2023-08-09 06:27 UTC, rvelaVenafi approved these changes

2023-08-09 06:27 UTC, merged