Feat: Add unit tests for Firefly GetCred.
Venafi/vcert pull request #396
Opened 2023-09-19 04:18 UTC by marcos-albornoz

- Add unit tests for firefly.Connector.Authorize()
- Fix a bug getting the AuthStatus for DevFlowGrant.

Closes VC-25642

2023-09-19 14:58 UTC, sbanic-venafi approved these changes
Since you are no longer just returning status based off of error.Error() string, if the error is not a reponseError you will now return many more "Unknown" statuses. Hopefully, that's intended. Unless most of these errors already are reponseError objects.

2023-09-20 18:37 UTC, luispresuelVenafi requested changes
enable these tests in the pipeline

2023-09-22 20:01 UTC, luispresuelVenafi approved these changes

2023-09-22 22:11 UTC, luispresuelVenafi requested changes
Pipeline failed with:
```
[2023-09-22T20:18:42.842Z] === RUN   TestNewResponseError
[2023-09-22T20:18:42.842Z]     error_test.go:39: failed to parse error message
[2023-09-22T20:18:42.842Z] --- FAIL: TestNewResponseError (0.00s)
```
Please fix.

2023-09-22 22:14 UTC, luispresuelVenafi approved these changes

2023-09-22 22:18 UTC, merged