[VC-31275] Allow user to configure the User-Agent HTTP header in vcert SDK
Venafi/vcert pull request #443
Opened 2024-03-27 11:40 UTC by wallrj

**Software like cert-manager can now supply its own User-Agent when it instantiates the vcert.Client.**
> Why? Because if there is a bug in the cert-manager Venafi issuer, which causes it to not back off in the event of a failed API request, the Venafi server administrator can quickly know that cert-manager is the culprit and quickly report the bug so that it be quickly fixed.

**The default User-Agent for `vcert` CLI and for any software importing the vcert/v5 is now: `vcert/v5`.**
> Why? Because right now the vcert CLI and any software that uses the vcert SDK will use the [default `Go-http-client/1.1` User-Agent header](https://github.com/golang/go/blob/db423dde85ad4923c2c4addb1cd96f119c7b6dc6/src/net/http/request.go#L534-L538) and the requests will be indistinguishable from any other Go http client.
The new default header will allow the Venafi administrator to estimate the adoption of vcert v5.

Fixes: https://github.com/Venafi/vcert/issues/437

* https://github.com/Venafi/vcert/issues/437
* VC-31275

## Testing
### `vcert` CLI default
```sh
export HTTPS_PROXY=localhost:8080
go run ./cmd/vcert renew     -k foo --no-prompt -id foo --trust-bundle ~/.mitmproxy/mitmproxy-ca.pem
```

```sh
vCert: 2024/03/27 10:54:54 Warning: --platform not set. Attempting to best-guess platform from connection flags
vCert: 2024/03/27 10:54:54 Detected trust bundle...
vCert: 2024/03/27 10:54:54 You specified a trust bundle.
vCert: 2024/03/27 10:54:55 Unable to connect to Venafi as a Service: vcert error: server error: 401 Unauthorized
vCert: 2024/03/27 10:54:55 Failed to fetch old certificate by id foo: must be autheticated to request a certificate
exit status 1
```

![image](https://github.com/Venafi/vcert/assets/978965/9a171cf2-252f-4ebc-ae56-c8d042d0f72b)

### Examples
I've partially tested the examples, in so far as I ran each example with some fake settings in environment variables and observed that the expected User-Agent header was present in the first failing request.

* firefly
![image](https://github.com/Venafi/vcert/assets/978965/b8bc09da-abbf-4f7e-a0c0-bca5fdab5920)

* server
![image](https://github.com/Venafi/vcert/assets/978965/74f32253-a471-4d19-a510-b8aa3f522c51)

* simple-cli
![image](https://github.com/Venafi/vcert/assets/978965/e0f0d116-ca5a-4559-b0a3-2e1fe1e88960)

* tlspc-svc-account
![image](https://github.com/Venafi/vcert/assets/978965/f9ee5ca4-cc97-4568-b391-3e12b909bc47)

2024-03-27 13:38 UTC, wallrj commented
/cc @rvelaVenafi 

Please review.

2024-03-28 15:57 UTC, rvelaVenafi requested changes

2024-03-28 15:57 UTC, rvelaVenafi commented on pkg/venafi/cloud/connector.go
> +	"github.com/go-http-utils/headers"
please move this import up. The import block format should be as follow:

```
native imports

third party imports

vcert imports
```

2024-03-28 15:57 UTC, rvelaVenafi commented on pkg/venafi/firefly/firefly.go
> +	"github.com/go-http-utils/headers"
same as previous comment. Please sort imports

2024-03-28 15:57 UTC, rvelaVenafi commented on pkg/venafi/tpp/tpp.go
> +	"github.com/go-http-utils/headers"
same s previous comments. Please sort imports

2024-03-28 17:46 UTC, rvelaVenafi approved these changes

2024-03-28 18:15 UTC, JigarAtVenafi approved these changes

2024-04-02 13:45 UTC, merged